# Generated by Django 5.2.1 on 2025-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HindiVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi_title', models.CharField(max_length=100)),
                ('hindi_author', models.CharField(max_length=100)),
                ('hindi_description', models.TextField(blank=True, null=True)),
                ('hindi_summary', models.TextField()),
            ],
        ),
    ]
