# Generated by Django 4.2.23 on 2025-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_hindiversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookPDF_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
